excel.path = C:/Users/HNL014/Downloads/Copy of AV_NoTP.xlsx
excel.sheet = Main
excel.shipment = A5
excel.status.cell = B5
gcss_profile_name = Ho Chi Minh Export CSA (MSL)
invoked_class = AV_RSM
time.unit.factor = 1
use.GUI = False
