username = HNL014
password = Xedap@123
excel.path = C:/Users/HNL014/Downloads/Duty.xlsx
excel.sheet = MainMenu
download.folder = C:\Users\HNL014\Downloads\a\down
rename.folder = C:\Users\HNL014\Downloads\a\rename
excel.column.fcr = A2
excel.column.fcr_rename = B2
invoked_class = Duty
time.unit.factor = 1
use.GUI = True
