username = 
password = 
excel.path = .\\input\duty.xlsx
excel.sheet = MainMenu
download.folder = .\\input
rename.folder = .\\input
excel.column.fcr = A2
excel.column.fcr_rename = B2
invoked_class = Duty
time.unit.factor = 1
use.GUI = False
