excel.path = C:/Users/HNL014/Downloads/test/test2.xlsx
excel.sheet = Sheet1
excel.shipment = A2
excel.status.trucking = B2
excel.status.cell = C2
invoked_class = GCSS_SPIR
time.unit.factor = 1
use.GUI = False
