excel.path = C:/Users/HNL014/Downloads/GCSS_automation_testcase.xlsx
excel.sheet = No_show_booking
excel.shipment = A2
excel.status.cell = B2
gcss_profile_name = Ho Chi Minh Export CSA (MSL)
gcss_prod = B
invoked_class = No_show_Booking_Cancellation
time.unit.factor = 1
use.GUI = False
