excel.path = C:/Users/HNL014/OneDrive - Maersk Group/1. AC/1. MACRO BUILD/3. TEST/test.xlsx
excel.sheet = Sheet1
folder_docs.folder = C:/Users/HNL014/OneDrive - Maersk Group/1. AC/1. MACRO BUILD/3. TEST
invoked_class = PDF_Grok_testing
time.unit.factor = 1
use.GUI = False
