excel.path=
excel.sheet=PDF_Combine
folder_bill.folder=
folder_doc.folder=
folder_output.folder=
excel.column.bill=A2
excel.column.cont=B2
invoked_class=PDFCombine_BillandCont
time.unit.factor=1
use.GUI=False
