excel.path = C:\Users\HNL014\Downloads\test\test.xlsx
excel.sheet = Sheet1
folder_docs.folder = C:\Users\HNL014\OneDrive\Desktop\FCR Combine\FCR DRAFF\CSC FCR\CSC FCR
invoked_class = PDFRead
time.unit.factor = 1
use.GUI = False
