username = huy.le@lns.maersk.com
password = Xedap@123
download.folder = C:\Users\HNL014\Downloads\down
excel.path = C:\Users\HNL014\Downloads\down\abc.xlsx
excel.sheet = Sheet1
excel.column.bill = A2
invoked_class = SCP_upload
time.unit.factor = 1
use.GUI = True
