github.pat=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
github.release.version=2022-11-28
github.release.latest.url=https://api.github.com/repos/Maersk-Global/automation_tool/releases/latest
